### PR TITLE
Contribution from Son

### PR DESCRIPTION
**Pull request by tshoang**
- Added bibentry (fixed some problem)
- A paragraph about different semantics.

### CODE REVIEW

**Comment by cfsnook** [comment]
The changes to translation.tex seem to revert many of my changes... i.e. simpler format of listings.
Is there something you intended to change in this file?

**Comment by tshoang** [comment]
Hi Colin,
 Oh I see. I see the changes for translations.tex and I thought that it was me who create the changes so I revert it back. Can you send me your copy of translations.tex? I will put it in again. I found that I can merge the pull request myself (if I want).
 Best,
Son

**Comment by cfsnook** [comment]
Good job you asked for a review then!



On 22 May 2018, at 18:18, Thái Sơn Hoàng <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Colin,
Oh I see. I see the changes for translations.tex and I thought that it was me who create the changes so I revert it back. Can you send me your copy of translations.tex? I will put it in again. I found that I can merge the pull request myself (if I want).
Best,
Son

**Comment by cfsnook** [comment]
much better!

**Pull request merged**
